apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: credential-data-pvc
  labels:
    app: kube-credential
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
